# Generated by Django 5.2.12 on 2026-05-28 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_username', models.CharField(max_length=100, unique=True, verbose_name='Имя пользователя в тг')),
                ('tg_chat_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя в тг')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт пользователя в ТГ',
                'verbose_name_plural': 'Аккаунты пользователей в ТГ',
            },
        ),
    ]
