# Generated by Django 5.2.9 on 2026-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'Фото слайдера', 'verbose_name_plural': 'Фотки слайдера'},
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(upload_to='home/slider/', verbose_name='Фото'),
        ),
    ]
